[package]
name = "airship-dcap-qvl-wasm"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
dcap-qvl = { version = "0.5.2", default-features = false, features = ["std", "js", "rustcrypto", "default-x509", "report"] }
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2.118"
wasm-bindgen-futures = "0.4.68"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"
