/**
 * Public surface of the ported continual harness. Mirrors
 * packages/coding-agent/src/core/refinement/ exports, minus the file-backed
 * persistence (replaced by the adapter-backed stores).
 */

export {
  HARNESS_EDIT_ACTIONS,
  HARNESS_ENTRY_KINDS,
  HARNESS_SCOPES,
  type HarnessAppliedEdit,
  type HarnessEditAction,
  type HarnessEntry,
  type HarnessEntryKind,
  type HarnessEntrySource,
  type HarnessProposal,
  type HarnessRefinementEdit,
  type HarnessRefinementEvent,
  type HarnessScope,
  type HarnessSkillReference,
  type HarnessSnapshot,
  type ValidationIssue,
} from "./types";
export {
  AUTO_REFINE_REVIEW_SYSTEM_PROMPT,
  AUTO_REFINE_REVIEW_TRAILER,
  REFINEMENT_SCOPE_INSTRUCTION_GLOBAL,
  REFINEMENT_SCOPE_INSTRUCTION_LOCAL,
  REFINEMENT_SYSTEM_PROMPT,
  REFINEMENT_USER_PROMPT_TRAILER,
  TRUNCATED_JSON_ERROR,
  type HarnessProposalJson,
} from "./prompt";
export {
  HARNESS_SCHEMA_VERSION,
  MAX_SLUG_LENGTH,
  HarnessApplyRejectedError,
  HarnessKvConflictError,
  IndexedDBHarnessStore,
  IndexedDbHarnessKvAdapter,
  InMemoryHarnessKvAdapter,
  InMemoryHarnessStore,
  HarnessStoreBase,
  OptimisticConcurrencyError,
  canonicalHarnessEntry,
  canonicalRefinementEvent,
  canonicalSkillReference,
  resolveHarnessRef,
  slugHarnessId,
  stableStringify,
  validateRefinementEdits,
  type HarnessEntryInput,
  type HarnessEntryPatch,
  type HarnessKvAdapter,
  type HarnessKvRecord,
  type HarnessKvWrite,
  type HarnessRefinementApplyOptions,
  type HarnessStore,
  type HarnessStoreOptions,
  type IndexedDbHarnessKvOptions,
  type PreparedRefinementEdit,
  type ValidatedRefinement,
} from "./store";
export {
  MAX_AUTO_REFINE_REVIEW_OUTPUT_TOKENS,
  MAX_AUTO_REFINE_REVIEW_TRAJECTORY_CHARS,
  MAX_PLANNER_HISTORY_EVENTS,
  MAX_PLANNER_OVERVIEW_ENTRIES_PER_KIND,
  MAX_PLANNER_OVERVIEW_FIELD_CHARS,
  MAX_REFINEMENT_OUTPUT_TOKENS,
  MAX_REFINEMENT_TRAJECTORY_CHARS,
  historyForPrompt,
  overviewForPrompt,
  parseHarnessProposal,
  planRefinement,
  reviewAutoRefine,
  type AutoRefineReview,
  type AutoRefineReviewContext,
  type AutoRefineReviewReason,
  type HarnessCompletionClient,
  type HarnessCompletionRequest,
  type HarnessCompletionResult,
  type HarnessRefinementPlan,
  type PlanRefinementInput,
  type ReviewAutoRefineInput,
} from "./planner";
export {
  DEFAULT_OVERVIEW_CONTENT_LIMIT,
  DEFAULT_OVERVIEW_ENTRY_LIMIT,
  DEFAULT_OVERVIEW_REFINEMENT_LIMIT,
  Harness,
  formatHarnessStateForPrompt,
  mergeHarnessScopes,
  type AutoRefineInput,
  type AutoRefineResult,
  type HarnessOverview,
  type HarnessPromptOptions,
  type RefineInput,
} from "./harness";
